### ISSUE TITLE
Errors with create-react-app

### ISSUE THREAD

**Issue by benjick** [yarnaimo/fireschema#36]
Hello!

This package looks really good and I look forward to using it, but I can't get it running. 

First I had this error: `Module '"fireschema"' has no exported member 'DataModel'.ts(2305)`. But I put a `// @ts-ignore` on it to get further.

Then secondly, when I run `yarn fireschema src/firebase/schema/index.ts` I get the following error:
```
/Users/foo/fireschema-test/src/firebase/schema/index.ts:12
import { z } from "zod";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Any suggestions what I can do? I put the code here if you want to check it out, but I haven't done much except initialize CRA and then install fireschema: https://github.com/benjick/fireschema-error

Thank you!

**Comment by Code-Hex** [comment]
@benjick Hi
I think you have to use "commonjs" at this line. It works fine for me.
https://github.com/benjick/fireschema-error/blob/e64c4c05ee917bc5c1e34dbec62bb5a6abd58dbb/tsconfig.json#L16

**Comment by benjick** [comment]
@Code-Hex thank you! That worked lovely, cheers!
